### ISSUE TITLE
Show the entire VC object with inputted JSON

### ISSUE THREAD

**Issue by CJGutz** [thomsen85/vc-inspector#21]
### Is your feature request related to a problem?

We are not able to validate the inspector. We need to have a quick response from inserted VCs.

### Describe the solution you would like

Show a  debug field for the VC outputted from the inspector
Logging to the console has a feature with dropdowns to expand a big object. Something similar would be useful.

### Acceptance Criteria

Text is updated according to updates to the input
No fields are hidden from the user.

**Comment by thomsen85** [comment]
Pr: #41 Closed this issue
